### PR TITLE
V1.9.0

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@jakirkham as I do not have permission to change the bot's PR I created this one with the suggestions.
After we integrate this PR we might integrate #18 as well

**Comment by jakirkham** [comment]
Sounds good. Could you please fix the merge conflicts? Then we can merge 🙂

**Comment by marcelotrevisani** [comment]
> Sounds good. Could you please fix the merge conflicts? Then we can merge slightly_smiling_face

Fixed!

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Pull request closed without merging**
